apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l8j57f404-go
  janus-idp.io/tekton: l8j57f404-go
  backstage.io/kubernetes-id: l8j57f404-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l8j57f404-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
